import { Inter } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
    weight: "900",
    subsets: ["latin"],
});
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pt-BR" className={roboto.className}>
            <body className={inter.className}>{children}</body>
        </html>
    );
}
